import type { RelationType } from './causal-relation.js';

export type SignalType = 'reinforce' | 'weaken' | 'create';
export type SignalDomain = 'ontological' | 'epistemological' | 'normative';
export type SignalStatus = 'pending' | 'applied' | 'conflicted' | 'stale';

// Domain priority for deterministic sort: lower number = higher priority in arbitration.
export const SIGNAL_DOMAIN_PRIORITY: Record<SignalDomain, number> = {
  ontological: 1,
  epistemological: 2,
  normative: 3,
};

// A causal signal is an observed hypothesis generated by a lifecycle event.
// It is NOT a fact. It lives in the signal layer until arbitration commits it
// to the graph or expires it. Queries never read this layer.
export interface CausalSignal {
  id: string;
  domain: SignalDomain;
  signal_type: SignalType;
  candidate_from: string;
  candidate_relation: RelationType;
  candidate_to: string;
  edge_id?: string;      // existing edge being reinforced/weakened, if applicable
  confidence: number;    // 0.0–1.0, reserved for future weighted arbitration
  event: string;         // e.g. "task_completed:TASK-184"
  source: 'system';
  status: SignalStatus;
  review_count: number;
  timestamp: string;
}

// Appended when signal status or review_count changes.
// Differentiated from CausalSignal by presence of 'signal_id' (no 'id').
export interface CausalSignalUpdate {
  signal_id: string;
  status: SignalStatus;
  review_count: number;
  timestamp: string;
}
